blog_show:
    path:      /
    defaults:  { _controller: BookstoreDemoBundle:Book:list, page: 1 }
    
bookstore_demo:
    resource: "@BookstoreDemoBundle/Controller/"
    type:     annotation
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"    

