services:    
    listener.number_format_changer:
         class: Bookstore\DemoBundle\Listener\NumberFormatChanger
         arguments: ["@twig"]
         tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
