Bookstore\DemoBundle\Entity\Book:
    properties:
        title:
            - NotBlank: ~
        author:
            - NotBlank: ~    
        price:
            - NotBlank: ~        
            - Type:
                type: double
                
Bookstore\DemoBundle\Entity\Category:
    properties:
        name:
            - NotBlank: ~