Bookstore\DemoBundle\Entity\Book:
    properties:
        title:
            - NotBlank: ~
        author:
            - NotBlank: ~    
        price:
            - NotBlank: ~        
            - Type:
                type: double
        categoriesWithPriority:
            - All:
                - Bookstore\DemoBundle\Validator\Constraints\UniqueInCollection:
                    propertyPath: priority
                    message: "Priorytety kategorii przypisanych do książki muszą być być unikalne"
                - Bookstore\DemoBundle\Validator\Constraints\UniqueInCollection:
                    propertyPath: category.id
                    message: "Kategorie przypisane do książki nie mogą się powtarzać"    
                
Bookstore\DemoBundle\Entity\Category:
    properties:
        name:
            - NotBlank: ~

Bookstore\DemoBundle\Entity\BookHasCategory:
    properties:
        priority:
            - NotBlank: ~        
            - Type:
                type: integer           